language: php
php:
  - 5.3.29
  - 5.4
  - 5.5
  - 5.6
  - hhvm
before_script:
  - make install
script:
  - make test
after_script:
  - make coveralls
matrix:
  allow_failures:
    - php:
      - hhvm
  fast_finish: true