dist: trusty
language: php
php:
  - 7
  - 5.6
before_script:
  - composer update
  - composer install --prefer-dist --no-interaction
script:
  - composer test
  - composer phar
after_script:
  - composer coveralls
matrix:
  fast_finish: true
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: ./dist/ringcentral.phar
  skip_cleanup: true
  on:
    php: 7
    tags: true
    repo: ringcentral/ringcentral-php